"""
Create 3x3 cache-comparison grids from per-split + total CSV files.

Expected input:
- 9 CSV files generated by cache_sim_source_seen.py for one dataset:
  8 split CSVs + 1 total CSV.

Outputs:
- suppression_grid.png
- redundancy_grid.png

Usage examples:
        python3 dash_scripts/plot_cache_grid.py --csv-glob 'dash_results/imc/univ1/cache_sim/source_seen/results_univ1_source_seen_top8_splits/*.csv' --total-csv dash_results/imc/univ1/cache_sim/source_seen/results_univ1_source_seen_top8.csv --out-dir dash_results/imc/univ1/cache_sim/source_seen/plots

    python3 dash_scripts/plot_cache_grid.py --csvs a.csv b.csv ... i.csv --out-dir dash_results/imc/univ1/cache_sim/source_seen/plots
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from glob import glob
from collections import defaultdict
from typing import Dict, List, Sequence


def load_rows(path: Path) -> List[Dict[str, float | str | int]]:
    required = {
        "cache",
        "capacity",
        "total",
        "suppression_rate",
        "forward_rate",
        "redundancy_rate",
        "necessary_forwards",
        "redundant_forwards",
        "evictions",
    }
    rows: List[Dict[str, float | str | int]] = []
    with path.open("r", newline="") as f:
        reader = csv.DictReader(f)
        cols = set(reader.fieldnames or [])
        missing = sorted(required - cols)
        if missing:
            raise ValueError(
                f"Invalid cache CSV {path}: missing columns {', '.join(missing)}"
            )
        for row in reader:
            rows.append(
                {
                    "cache": row["cache"],
                    "capacity": float(row["capacity"]),
                    "total": int(row["total"]),
                    "suppression": float(row["suppression_rate"]),
                    "redundancy": float(row["redundancy_rate"]),
                }
            )
    return rows


def group_policies(rows: Sequence[Dict[str, float | str | int]]):
    bounded = [r for r in rows if float(r["capacity"]) > 0]
    policies = defaultdict(list)
    for r in bounded:
        policies[str(r["cache"])].append(r)
    for k in policies:
        policies[k].sort(key=lambda x: float(x["capacity"]))
    return dict(policies)


def discover_csvs(args: argparse.Namespace) -> List[Path]:
    paths: List[Path] = []
    for c in args.csvs:
        paths.append(Path(c))

    if args.csv_glob:
        for p in sorted(glob(args.csv_glob)):
            pp = Path(p)
            if pp.is_file():
                paths.append(pp)

    if args.total_csv:
        paths.append(Path(args.total_csv))

    # De-duplicate while preserving order
    seen = set()
    ordered: List[Path] = []
    for p in paths:
        key = str(p.resolve()) if p.exists() else str(p)
        if key in seen:
            continue
        seen.add(key)
        ordered.append(p)

    if len(ordered) != 9:
        raise ValueError(
            f"Need exactly 9 CSV files (8 split + 1 total), found {len(ordered)}"
        )
    for p in ordered:
        if not p.exists():
            raise FileNotFoundError(f"Missing CSV file: {p}")
    return ordered


def plot_grid(csv_paths: Sequence[Path], out_dir: Path, show: bool) -> None:
    import matplotlib

    if not show:
        matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    out_dir.mkdir(parents=True, exist_ok=True)

    fig_s, axs_s = plt.subplots(3, 3, figsize=(18, 14), sharex=True, sharey=True)
    fig_r, axs_r = plt.subplots(3, 3, figsize=(18, 14), sharex=True, sharey=True)

    for i, path in enumerate(csv_paths):
        rows = load_rows(path)
        policies = group_policies(rows)
        r_idx = i // 3
        c_idx = i % 3
        ax_s = axs_s[r_idx, c_idx]
        ax_r = axs_r[r_idx, c_idx]

        for name, group in sorted(policies.items()):
            xs = [float(r["capacity"]) for r in group]
            ys_sup = [100.0 * float(r["suppression"]) for r in group]
            ys_red = [100.0 * float(r["redundancy"]) for r in group]
            ax_s.plot(xs, ys_sup, linewidth=1.4, marker="o", markersize=2.5, label=name)
            ax_r.plot(xs, ys_red, linewidth=1.4, marker="o", markersize=2.5, label=name)

        ax_s.set_xscale("log", base=2)
        ax_r.set_xscale("log", base=2)
        ax_s.set_ylim(0, 105)
        ax_r.set_ylim(-5, 105)
        ax_s.grid(True, which="both", alpha=0.25)
        ax_r.grid(True, which="both", alpha=0.25)
        ax_s.set_title(path.stem, fontsize=9)
        ax_r.set_title(path.stem, fontsize=9)

    fig_s.suptitle("Suppression Rate by Split/Total (3x3)", fontsize=14)
    fig_r.suptitle("Redundancy Rate by Split/Total (3x3)", fontsize=14)

    for ax in axs_s[2, :]:
        ax.set_xlabel("Capacity")
    for ax in axs_r[2, :]:
        ax.set_xlabel("Capacity")
    for ax in axs_s[:, 0]:
        ax.set_ylabel("Suppression (%)")
    for ax in axs_r[:, 0]:
        ax.set_ylabel("Redundancy (%)")

    handles, labels = axs_s[0, 0].get_legend_handles_labels()
    if handles:
        fig_s.legend(handles, labels, loc="upper center", ncol=6, fontsize=8, bbox_to_anchor=(0.5, 0.98))
        fig_r.legend(handles, labels, loc="upper center", ncol=6, fontsize=8, bbox_to_anchor=(0.5, 0.98))

    fig_s.tight_layout(rect=(0, 0, 1, 0.95))
    fig_r.tight_layout(rect=(0, 0, 1, 0.95))

    out_s = out_dir / "suppression_grid_3x3.png"
    out_r = out_dir / "redundancy_grid_3x3.png"
    fig_s.savefig(out_s, dpi=150)
    fig_r.savefig(out_r, dpi=150)
    print(f"Saved {out_s}")
    print(f"Saved {out_r}")

    if show:
        plt.show()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--csvs", nargs="*", default=[], help="Explicit list of CSV files")
    ap.add_argument("--csv-glob", default="", help="Glob for split CSV files")
    ap.add_argument("--total-csv", default="", help="Total aggregated CSV")
    ap.add_argument("--out-dir", default="dash_results/imc/univ1/cache_sim/source_seen/plots", help="Output directory")
    ap.add_argument("--show", action="store_true", help="Show interactively")
    args = ap.parse_args()

    csv_paths = discover_csvs(args)
    plot_grid(csv_paths, Path(args.out_dir), args.show)


if __name__ == "__main__":
    main()
