#!/usr/bin/env python3
"""
Plot cache pressure curves from capacity CSV outputs produced by cache simulators.

Each figure corresponds to one cache policy; each curve is a cache capacity.
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt


def parse_capacities(text: str) -> List[int]:
    vals: List[int] = []
    for token in text.split(","):
        token = token.strip()
        if not token:
            continue
        vals.append(int(token))
    return vals


def sanitize(name: str) -> str:
    out = "".join(ch if ch.isalnum() or ch in ("_", "-", ".") else "_" for ch in name)
    return out.strip("._-") or "cache"


def load_rows(path: Path) -> Dict[Tuple[str, int], List[Tuple[int, int, float]]]:
    grouped: Dict[Tuple[str, int], List[Tuple[int, int, float]]] = defaultdict(list)
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        required = {"cache", "capacity", "record_index", "timestamp_ps", "fill_percent"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing columns in capacity CSV: {sorted(missing)}")
        for row in reader:
            cache = (row.get("cache") or "").strip()
            if not cache:
                continue
            cap = int(float(row["capacity"]))
            rec_idx = int(float(row["record_index"]))
            ts_ps = int(float(row["timestamp_ps"]))
            fill_pct = float(row["fill_percent"])
            grouped[(cache, cap)].append((rec_idx, ts_ps, fill_pct))
    return grouped


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("capacity_csv", help="Capacity CSV generated by cache_sim*_int.py")
    ap.add_argument("--out-dir", default="", help="Output directory for PNGs (default: <csv_dir>/plots)")
    ap.add_argument("--prefix", default="capacity_pressure", help="Output filename prefix")
    ap.add_argument(
        "--capacities",
        default="",
        help="Comma-separated explicit capacities to plot (example: 512,1024,2048)",
    )
    ap.add_argument(
        "--min-capacity",
        type=int,
        default=512,
        help="Minimum capacity to include when --capacities is not provided",
    )
    ap.add_argument(
        "--x-axis",
        choices=["time", "record"],
        default="time",
        help="Use packet timestamp (time) or record index on x-axis",
    )
    args = ap.parse_args()

    csv_path = Path(args.capacity_csv)
    if not csv_path.is_file():
        raise FileNotFoundError(f"Capacity CSV not found: {csv_path}")

    out_dir = Path(args.out_dir) if args.out_dir else csv_path.parent / "plots"
    out_dir.mkdir(parents=True, exist_ok=True)

    grouped = load_rows(csv_path)
    wanted_caps = set(parse_capacities(args.capacities)) if args.capacities else None

    by_cache: Dict[str, Dict[int, List[Tuple[int, int, float]]]] = defaultdict(dict)
    for (cache_name, cap), rows in grouped.items():
        if wanted_caps is not None:
            if cap not in wanted_caps:
                continue
        else:
            if cap < args.min_capacity:
                continue
        by_cache[cache_name][cap] = sorted(rows, key=lambda t: t[0])

    if not by_cache:
        print("No capacity series matched the selected capacities; skipping plots.")
        return

    for cache_name, cap_map in sorted(by_cache.items(), key=lambda kv: kv[0]):
        if not cap_map:
            continue
        plt.figure(figsize=(9.0, 5.0))
        for cap in sorted(cap_map.keys()):
            rows = cap_map[cap]
            if args.x_axis == "record":
                x_vals = [r[0] for r in rows]
                x_label = "Record Index"
            else:
                # Convert picoseconds to milliseconds for readability.
                x_vals = [r[1] / 1_000_000_000.0 for r in rows]
                x_label = "Time (ms)"
            y_vals = [r[2] for r in rows]
            plt.plot(x_vals, y_vals, linewidth=1.3, label=f"cap={cap}")

        plt.xlabel(x_label)
        plt.ylabel("Cache Fill (%)")
        plt.ylim(0.0, 100.0)
        plt.title(f"Cache Pressure: {cache_name}")
        plt.grid(True, alpha=0.25)
        plt.legend(loc="best", fontsize=8)
        plt.tight_layout()

        out_file = out_dir / f"{args.prefix}_{sanitize(cache_name)}.png"
        plt.savefig(out_file, dpi=180)
        plt.close()
        print(f"Wrote: {out_file}")


if __name__ == "__main__":
    main()
