"""
Split IMC packet-table txt files into per-sink shards.

Input should be the text table generated by convert_imc_pcap_to_txt.py.
By default, sink is taken from the dst_ip column.
"""

from __future__ import annotations

import argparse
import csv
import ipaddress
import re
from collections import OrderedDict
from glob import glob
from pathlib import Path
from typing import Dict, List, Sequence, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_path", help="Input txt file or directory.")
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory for per-sink output files.",
    )
    parser.add_argument(
        "--pattern",
        default="*.txt",
        help="Glob pattern when input_path is a directory (default: %(default)s).",
    )
    parser.add_argument(
        "--sink-column",
        default="dst_ip",
        help="Column name used as sink id (default: %(default)s).",
    )
    parser.add_argument(
        "--ip-prefix-len",
        type=int,
        default=0,
        help="If >0, group IPv4 sink addresses by this prefix length (e.g., 16 or 24).",
    )
    parser.add_argument(
        "--max-open-files",
        type=int,
        default=128,
        help="Maximum sink files kept open at once (default: %(default)s).",
    )
    parser.add_argument(
        "--max-rows",
        type=int,
        default=0,
        help="Maximum rows to process (0 means all).",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=0,
        help="Keep only top-K sinks by row count (0 means keep all).",
    )
    parser.add_argument(
        "--file-prefix",
        default="sink",
        help="Output filename prefix before sink id (default: %(default)s).",
    )
    return parser.parse_args()


def sniff_delimiter(path: Path) -> str:
    with path.open("r", encoding="utf-8", newline="") as f:
        header = f.readline()
    if "\t" in header:
        return "\t"
    if "," in header:
        return ","
    return "\t"


def resolve_inputs(input_path: Path, pattern: str) -> List[Path]:
    if input_path.is_file():
        return [input_path]
    if not input_path.is_dir():
        raise FileNotFoundError(f"Input path does not exist: {input_path}")
    files = [Path(p) for p in glob(str(input_path / pattern)) if Path(p).is_file()]
    files.sort(key=lambda p: p.name)
    if not files:
        raise FileNotFoundError(f"No matching files under {input_path} with pattern {pattern}")
    return files


def sanitize_sink_for_filename(sink: str) -> str:
    clean = sink.strip()
    if not clean:
        clean = "EMPTY"
    clean = re.sub(r"[^A-Za-z0-9._-]", "_", clean)
    return clean


def normalize_sink(raw_sink: str, ip_prefix_len: int) -> str:
    sink = raw_sink.strip()
    if not sink:
        return ""
    if ip_prefix_len <= 0:
        return sink
    try:
        addr = ipaddress.ip_address(sink)
    except ValueError:
        return sink

    max_prefix = 32 if addr.version == 4 else 128
    prefix_len = min(max(0, ip_prefix_len), max_prefix)
    network = ipaddress.ip_network(f"{addr}/{prefix_len}", strict=False)
    return f"{network.network_address}/{prefix_len}"


class WriterCache:
    def __init__(
        self,
        output_dir: Path,
        fieldnames: Sequence[str],
        max_open_files: int,
        file_prefix: str,
    ):
        self.output_dir = output_dir
        self.fieldnames = list(fieldnames)
        self.max_open_files = max_open_files
        self.file_prefix = file_prefix
        self.cache: "OrderedDict[str, Tuple[object, csv.DictWriter]]" = OrderedDict()
        self.rows_per_sink: Dict[str, int] = {}

    def _open_writer(self, sink: str) -> csv.DictWriter:
        sink_name = sanitize_sink_for_filename(sink)
        out_path = self.output_dir / f"{self.file_prefix}_{sink_name}.txt"
        is_new = not out_path.exists()
        handle = out_path.open("a", encoding="utf-8", newline="")
        writer = csv.DictWriter(handle, fieldnames=self.fieldnames, delimiter="\t")
        if is_new:
            writer.writeheader()
        self.cache[sink] = (handle, writer)
        self.rows_per_sink[sink] = self.rows_per_sink.get(sink, 0)
        return writer

    def get_writer(self, sink: str) -> csv.DictWriter:
        if sink in self.cache:
            handle, writer = self.cache.pop(sink)
            self.cache[sink] = (handle, writer)
            return writer

        if len(self.cache) >= self.max_open_files:
            _, (old_handle, _) = self.cache.popitem(last=False)
            old_handle.close()

        return self._open_writer(sink)

    def write_row(self, sink: str, row: Dict[str, str]) -> None:
        writer = self.get_writer(sink)
        writer.writerow(row)
        self.rows_per_sink[sink] = self.rows_per_sink.get(sink, 0) + 1

    def close_all(self) -> None:
        for handle, _ in self.cache.values():
            handle.close()
        self.cache.clear()


def main() -> None:
    args = parse_args()
    input_path = Path(args.input_path)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    files = resolve_inputs(input_path, args.pattern)
    print(f"Processing {len(files)} input file(s)")

    total_rows = 0
    written_rows = 0
    skipped_rows = 0
    sink_counts: Dict[str, int] = {}
    fieldnames: Sequence[str] | None = None

    for file_index, path in enumerate(files, start=1):
        delimiter = sniff_delimiter(path)
        with path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f, delimiter=delimiter)
            if reader.fieldnames is None:
                continue
            if fieldnames is None:
                fieldnames = reader.fieldnames

            for row in reader:
                if args.max_rows > 0 and total_rows >= args.max_rows:
                    break
                total_rows += 1

                sink = normalize_sink((row.get(args.sink_column) or ""), args.ip_prefix_len)
                if not sink:
                    skipped_rows += 1
                    continue
                sink_counts[sink] = sink_counts.get(sink, 0) + 1
                written_rows += 1

        print(f"  [{file_index}/{len(files)}] {path.name}: processed rows so far={total_rows:,}")

        if args.max_rows > 0 and total_rows >= args.max_rows:
            break

    if written_rows == 0:
        sinks = {}
    else:
        if fieldnames is None:
            raise RuntimeError("No input columns discovered from source files")
        sorted_sinks = sorted(sink_counts.items(), key=lambda kv: kv[1], reverse=True)
        if args.top_k > 0:
            selected = {sink for sink, _ in sorted_sinks[: args.top_k]}
        else:
            selected = {sink for sink, _ in sorted_sinks}

        writer_cache = WriterCache(
            output_dir=output_dir,
            fieldnames=fieldnames,
            max_open_files=args.max_open_files,
            file_prefix=args.file_prefix,
        )
        try:
            seen_rows = 0
            for path in files:
                delimiter = sniff_delimiter(path)
                with path.open("r", encoding="utf-8", newline="") as f:
                    reader = csv.DictReader(f, delimiter=delimiter)
                    for row in reader:
                        if args.max_rows > 0 and seen_rows >= args.max_rows:
                            break
                        seen_rows += 1
                        sink = normalize_sink((row.get(args.sink_column) or ""), args.ip_prefix_len)
                        if not sink or sink not in selected:
                            continue
                        writer_cache.write_row(sink, row)
                if args.max_rows > 0 and seen_rows >= args.max_rows:
                    break
        finally:
            writer_cache.close_all()
        sinks = writer_cache.rows_per_sink
    print("Done.")
    print(f"  Rows seen:           {total_rows:,}")
    print(f"  Rows written:        {written_rows:,}")
    print(f"  Rows skipped:        {skipped_rows:,}")
    print(f"  Unique sinks:        {len(sinks):,}")
    print(f"  Output directory:    {output_dir}")

    top = sorted(sinks.items(), key=lambda kv: kv[1], reverse=True)[:10]
    if top:
        print("  Top sinks:")
        for sink, count in top:
            print(f"    {sink}: {count:,}")


if __name__ == "__main__":
    main()
